### ISSUE TITLE
Example sponsorship: Nucleus BVBA

### ISSUE THREAD

**Issue by mattiasgeniar** [mattiasgeniar/CronWeekly.com#1]
## Getting started

Please fill in the following information.
1. Your name: Mattias Geniar
2. Your company name: Nucleus BVBA
3. What [advertising pack](https://github.com/mattiasgeniar/CronWeekly.com) would you want: Silver
4. When would you like to start advertising: 1st issue of May
5. Preferred payment method: banktransfer
6. What link/service do you want to promote: Our new hosting offering with free (Let's Encrypt) SSL certificates. The link is [here](https://www.nucleus.be/en/blog/free-ssl-certificates-for-all-customers/)
7. Optional: a text to be included with the link:

Looking for a new hosting provider? Look no further: Nucleus has been a top hosting provider for the last 15 years, always innovating and expanding the quality of our service. Right now, all our [shared hosting can get a free Let's Encrypt based SSL certificate](https://www.nucleus.be/en/blog/free-ssl-certificates-for-all-customers/) right out of the box.
## TODO
- [x] Determine a date to start advertising
- [x] Receive link + title + paragraph for the text
- [x] Decide on advertising pack (Bronze/Silver/Gold): Silver
- [ ] Send newsletter with link included
- [ ] Receive payment
