### ISSUE TITLE
Papertrail

### ISSUE THREAD

**Issue by troy** [mattiasgeniar/CronWeekly.com#2]
## Getting started

Please fill in the following information.

1. Your name: Troy Davis
2. Your company name: Papertrail
3. What [advertising pack](https://github.com/mattiasgeniar/CronWeekly.com) would you want: Silver
4. When would you like to start advertising: immediately
5. Preferred payment method: PayPal, Square Cash, or pretty much anything electronic would be ideal (I'll pay the fees); SWIFT bank transfer also possible
6. What link/service do you want to promote: Papertrail's hosted log management service (https://papertrailapp.com/). Specific destination URLs are below.

7. Optional: a text to be included with the link:

### 1 of 4 (Tools & Projects)

With Papertrail's free plan, receive a Slack, HipChat, or HTTP webhook notification when a new user signs up for your Web app, a process segfaults, or an admin invokes `sudo`.
Link URL: `https://papertrailapp.com/?utm_source=cronweekly&utm_medium=email&utm_campaign=list`

### 2 of 4 (Guides & Tutorials)

Since there's only one of you, it should be easy for support staff and developers to learn from log messages. Here's how to generate a link from your admin dashboard to see logged requests from an certain user or IP.
Link URL: `http://help.papertrailapp.com/kb/how-it-works/linking-to-logs/#example?utm_source=cronweekly&utm_medium=email&utm_campaign=list`

### 3 of 4 (Tools & Projects)

Papertrail uses Papertrail. Here's a few specific design decisions which make life easier for Papertrail's team.
Link URL: `https://papertrailapp.com/tour/viewer?utm_source=cronweekly&utm_medium=email&utm_campaign=list`

### 4 of 4 (News)

I'll provide this between now and the 4th run, so that it will be recent.

## TODO
- [X] Determine a date to start advertising
- [X] Receive link + title + paragraph for the text
- [X] Decide on advertising pack (Bronze/Silver/Gold)
- [x] Send newsletter with link included
- [x] Receive payment

**Comment by mattiasgeniar** [comment]
Thanks again for the sponsorship Troy, I'm happy to close this issue!
